### ISSUE TITLE
Include edisgo grid expansion parameter `timesteps_pfa` in scenario_settings

### ISSUE THREAD

**Issue by birgits** [openego/eGo#112]
I changed the parameter `timesteps_pfa` for the grid reinforcement costs calculation after curtailment and storage integration to only be conducted for the two worst time steps at the HV/MV substation (see   [here](https://github.com/openego/eGo/blob/dev/ego/tools/edisgo_integration.py#L786)) in order to reduce computation time. As we haven't further analysed if this is a valid option @ulfmueller and I thought it would be better to add this parameter to the scenario_settings and leave it to the user to decide wether to use it or include all timesteps in determination of grid expansion needs. @maltesc could you please do this?

**Comment by maltesc** [comment]
I have just included this change in the settings (dev): https://github.com/openego/eGo/blob/b1fc26ecc9581c054582f1bb4502c0bbab6f725f/ego/scenario_setting.json#L56
The effect takes place here: https://github.com/openego/eGo/blob/b1fc26ecc9581c054582f1bb4502c0bbab6f725f/ego/tools/edisgo_integration.py#L793
