### ISSUE TITLE
Versioning for Integration of eTraGo and eDisGo

### ISSUE THREAD

**Issue by maltesc** [openego/eGo#12]
Currently the interface between eTraGo and eDisgo works only via the database (see: [specs.py](https://github.com/openego/eGo/blob/features/specs/ego/tools/specs.py)).

In order to truly integrate both programs into eGo, some version issues need to be solved:

 [eTraGo install requirements](https://github.com/openego/eTraGo/blob/dev/setup.py)
 [eDisGo install requirements](https://github.com/openego/eDisGo/blob/dev/setup.py)

Most important seem to be 1) PyPSA 2) Pandas and apparently 3) egoio

**Comment by wolfbunke** [comment]
All modules works know on the same version. For the installation see special notes [here](http://openego.readthedocs.io/en/latest/getting_started.html) and check you[ package dependencies](https://github.com/openego/eGo/blob/dev/ego_dependencies.txt).
