### ISSUE TITLE
Implementing line optimization and line extension in eTraGo and eGo

### ISSUE THREAD

**Issue by wolfbunke** [openego/eGo#13]
Todos:
- test the features/lines_optimization and implement it into eTraGo
  - update eTraGo version in features/lines_optimization
  - add cost assumptions and  other parameters into the OEDB
  - implement calculations as functions 
  - ...

Branch: 
https://github.com/openego/eTraGo/tree/features/lines_optimization

**Comment by ulfmueller** [comment]
Why is this issue not in eTraGo?

**Comment by wolfbunke** [comment]
Your right, I will move it to eTraGo. Part of the tasks is already in Part of the tasks is already in [#104](https://github.com/openego/eTraGo/issues/104)

**Comment by wolfbunke** [comment]
Its moved to  [#104](https://github.com/openego/eTraGo/issues/104)
