### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by wolfbunke** [openego/eGo#141]
I would like to schedule the Documentation and fixes release of eGo respectively with all dependencies of eTraGo, eDisGo, ding0, ego.io within the project of open_eGo.

The idea of the Release schedule is:

- eTrago on the 24.10.18 (ok, from @ulfmueller, @ClaraBuettner )
- eDisGo on the 23.10.18 (Ok, from @birgits )
- Dingo on the 22.-23.10.18 (@birgits will talk with @nesnoj )
- ego.io should be okay with actual version (or?)
- eGo on the 25.10.18 (ok, form @wolfbunke )

What do you think?

**Comment by birgits** [comment]
ding0 and eDisGo releases are done! I hope everything works ;)

**Comment by ulfmueller** [comment]
eTraGo 0.7.1 is now released :tada:

**Comment by wolfbunke** [comment]
nice :star2:  :raised_hands:

**Comment by wolfbunke** [comment]
eGo is released https://pypi.org/project/eGo/
