### ISSUE TITLE
Implement logging in eGo

### ISSUE THREAD

**Issue by wolfbunke** [openego/eGo#15]
implement and use logging in eGo

see: 
- http://docs.python-guide.org/en/latest/writing/logging/
- https://docs.python.org/3/library/logging.html

**Comment by Ludee** [comment]
I just recently implemented a revised logging function for another project.

See (and copy) from [here](https://github.com/ReeemProject/reeem_db/blob/master/database_adapter/reeem_io.py#L24-L54)

I had some trouble with duplicate entries in the console and solved it with 
`sys.tracebacklimit = 0`

**Comment by wolfbunke** [comment]
Thanks for your hint!

**Comment by Ludee** [comment]
You're welcome!

I didn't implement other "levels" than INFO.
Because I didn't really understand how and there was need for it.
So perhaps you can have a look at this:
https://docs.python.org/3/library/logging.html#levels

**Comment by wolfbunke** [comment]
Function `define_logging()` is implemented in https://github.com/openego/eGo/blob/dev/ego/tools/utilities.py#L34
