### ISSUE TITLE
Define eGo app

### ISSUE THREAD

**Issue by lukasol** [openego/eGo#2]
according to WP 5.1

we need a file that calculates total system costs considering the results of eTraGo and eDisGo.

**Draft of folder and file structure:**

- [x]  **eGo/**
  - [x] readme.rst
  - [x] setup.py
  - [x] requirements.txt
- [x] **eGo/ego/**
  - [x] ego_main.py
- [ ] **eGo/ego/examples**
    - [ ] eDisGo
    - [ ] eTraGo
    - [ ] renpassG!S
- [x] **eGo/ego/tools/**
  - [x] economics.py
  - [x] plots.py
  - [x] results.py
  - [ ] ...
- [x] **eGo/doc/**
  - [x] index.rst
  - [ ] eGo_UML.graphml
  - [ ] ...

**Comment by lukasol** [comment]
25.7.: @wolfbunke gives first approach and receives feedback at webco.

**Comment by wolfbunke** [comment]
With the first release the first app structure is implemented
