### ISSUE TITLE
Function bus_id to mv_grid_id for ding0 grids integration

### ISSUE THREAD

**Issue by wolfbunke** [openego/eGo#22]
In order to implement a iteration of the ding0 grids a function wgich creates the relation between  bus_id and mv_grid_id or a relation table is needed. 

The SQL code for this looks as following: 

```
﻿SELECT
bus.bus_id,
grid.subst_id
FROM
grid.ego_dp_mv_griddistrict grid,
grid.ego_pf_hv_bus bus
WHERE
ST_Intersects(grid.geom, ST_Transform(bus.geom,3035))
AND bus.scn_name ='NEP 2035'
AND grid.version = 'v0.3.0'
AND bus.version = 'v0.3.0'
```

**Comment by maltesc** [comment]
I have implemented something similar some time ago.
I will re-implement this into an ego-function so the code is available globally....

**Comment by wolfbunke** [comment]
thanks!
