### ISSUE TITLE
Annualization of expansion costs in eDisGo and eTraGo

### ISSUE THREAD

**Issue by wolfbunke** [openego/eGo#33]
Are there any differences between the two models in terms of cost calculation?
Where in the code are those cost assumption met and what are those assumption?
Do they have to be harmonized ?

**Comment by ulfmueller** [comment]
in eTraGo we use... 

- for the storage investments:
![grafik](https://user-images.githubusercontent.com/16224592/38561228-c2f23350-3cd7-11e8-91f8-3d9bd4c4e6ea.png)
leading to the corresponding costs defined in the data processing:
-- https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_lopf_data.sql#L138
-- https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_lopf_data.sql#L188
-- https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_lopf_data.sql#L239
--  and so on
-  for the grid infrastructure investments (function can be used also more generally):
https://github.com/openego/eTraGo/blob/feature/network_variances/etrago/tools/utilities.py#L534-L556
@ClaraBuettner which table in the oedb is used for the overnight capital costs for the grid infrastructure (lines/cables/tranformer)?

**Comment by wolfbunke** [comment]
The grid cost function can be found here: http://edisgo.readthedocs.io/en/dev/api/edisgo.grid.html#edisgo.grid.network.Results.grid_expansion_costs.

**Comment by wolfbunke** [comment]
The parameters can be found on github here: https://github.com/openego/eDisGo/blob/dev/edisgo/config/config_grid_expansion_default.cfg#L77-L102 and the function here: https://github.com/openego/eDisGo/blob/dev/edisgo/flex_opt/costs.py. For the beginning it looks that the costs parameter of eTraGo and eDisGo are a bit different.

**Comment by wolfbunke** [comment]
The operational costs of the MV grids are calculated via pypsa or?
 @birgits @boltbeard @gplssm

**Comment by gplssm** [comment]
Actually, we don't consider for operational cost in eDisGo. As we don't determine the dispatch based on marginal cost, operational cost data is not needed. Costs that are assessed comprise of investment cost into new line and transformer equipment.

**Comment by wolfbunke** [comment]
ok, thx for the quick answer!

**Comment by wolfbunke** [comment]
The annualization of expansion is already  implemented in eGo for both models .  See: https://github.com/openego/eGo/blob/dev/ego/tools/economics.py
