### ISSUE TITLE
Clustering and parallelization of Ding0 grids

### ISSUE THREAD

**Issue by wolfbunke** [openego/eGo#34]
For a complete calculation of all ding0 grids and considering the computation time cluster possibilities and clusters / representative type grids were created for eDisGo / Ding0.

Can representative grids be automatically created / determined in eDisGo?

How many mv grids needs to be calculated?
Is it possible to parallelize these calculations?
What is the current state of clustering of Ding0 grids?

**Comment by ulfmueller** [comment]
see also #24 

one add-on question in this context which goes beyond the questions mentioned here so far is how we want to consider which parameters from eTraGo for the eDisGo clustering?

@gplssm @birgits Should we plan the todos and not-todos :wink: together? How are your plans on this issue?
On our next webco on Tuesday we could discuss this more in detail. But it would be nice if we could prepare s.th. beforehand to make the webco more efficient.

**Comment by gplssm** [comment]
Currently, we are blocked by non-project work. How about a short telco on Friday (something between 10.30 and 17.00)?

**Comment by ulfmueller** [comment]
like the idea. But I myself am on a wedding on Friday. Either you talk with @wolfbunke or we talk on Monday s.th between 11 and 17?

**Comment by gplssm** [comment]
I would prefer to include  @ulfmueller in the discussion, because clustering at MV level needs to be coordinated with network clustering at higher voltage levels. How about Monday at 4 PM?

**Comment by ulfmueller** [comment]
Perfect.

**Comment by ulfmueller** [comment]
I would recommend that @maltesc is part of the meeting as well?!

**Comment by gplssm** [comment]
Why not!? He/you can decide. I wouldn't mind.

**Comment by maltesc** [comment]
OK, sounds good, I'm in!

**Comment by wolfbunke** [comment]
ok, monday 4 pm

**Comment by maltesc** [comment]
I am currently working on the implementation of the MV grid clustering in eGo. 

For now, I am focusing on the simpler clustering method with the attributes _wind_ and _solar capacity_ and _farthest node_. Furthermore, I will add the option to consider eTraGo's _storage expansion_ as a clustering attribute.

An open questions is still the consideration of **eDisGo's parallelization**. @gplssm: As far as I can see, there is no option to use the specs in combination with the parallelization? Therefore I would focus on the loop-implementation (similar to what I did in my thesis) and add the parallelization functionality later...

**Comment by maltesc** [comment]
For my Master thesis I already implemented an eDisGo iteration (see https://github.com/openego/eGo/blob/features/corr/ego/corr_edisgo.py). 

This topic is furthermore related to https://github.com/openego/eGo/issues/27

**Comment by gplssm** [comment]
Please enjoy [eDisGo v0.0.3](https://github.com/openego/eDisGo/releases/tag/v0.0.3) including a [parallelization for custom function](https://edisgo.readthedocs.io/en/dev/quickstart.html#parallelization) and [other important changes](https://edisgo.readthedocs.io/en/dev/whatsnew.html#release-v0-0-3).
