### ISSUE TITLE
disaggregation meets eDisGo interface

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGo#39]
@gnn implemented a 'simple' disaggregation method. Of course we tried to meet the requirements of the eTraGo-eDisGo interface since it is designed for it. The correct operation has to be checked. The eTraGo branch on which the disagg-uniform is [working](https://github.com/openego/eTraGo/tree/features/disagg-uniform)

**Comment by maltesc** [comment]
After implementing the basic eDisGo integration in eGo, I will test the eTrago desaggregation. Fundamentally, I think it makes sense to leave this functionality in eTraGo. Thereby, the interface would remain 'blind' with regard to the actual desaggregation...
