### ISSUE TITLE
Add investment costs of  grid measures for 110 kV

### ISSUE THREAD

**Issue by wolfbunke** [openego/eGo#4]
Add investment costs of  grid measures for 110 kV:
see: https://github.com/openego/eGo/blob/investment_costs/ego/data/Investition_costs_of_grid_%20measures.csv

**Comment by wolfbunke** [comment]
@kropsi92 could you please insert your cost assumption to the CSV and add your sources. Thx!

**Comment by kropsi92** [comment]
16,"AC-Freileitungen",110-kV-Stromkreisauflage/Umbeseilung,"0,06",Mio. €/km,auf Bestandsleitung pro Stromkreis, dena Verteilnetzstudie 2030 S.146 ,https://shop.dena.de/sortiment/detail/produkt/dena-verteilnetzstudie-ausbau-und-innovationsbedarf-der-stromverteilnetze-in-deutschland-bis-2030/
17,"AC-Freileitungen",110-kV-Neubau in bestehender Trasse Doppelleitung,"0,52",Mio. €/km,inkl. Rückbau der bestehenden Trasse,dena Verteilnetzstudie 2030 S.146 ,https://shop.dena.de/sortiment/detail/produkt/dena-verteilnetzstudie-ausbau-und-innovationsbedarf-der-stromverteilnetze-in-deutschland-bis-2030/

**Comment by wolfbunke** [comment]
thx

**Comment by wolfbunke** [comment]
merged branch to dev

**Comment by wolfbunke** [comment]
The Costs are stored in the model_draft see[ here](https://github.com/openego/data_processing/commit/cf4d56a772cb2d2adb59ceb1631cc7d3db71fda3) and will be part of the preprocessing of the data processing.
