### ISSUE TITLE
Move disagg functionality to eGo

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGo#40]
We have been developing disaggregation methods in eTraGo. Since this functionality is mainly motivated by the interface requirements regarding eDisGo it might make sense to shift this functionality to eGo. The current disagg-uniform does not disaggregate power flows but only the nodal results, thus the result are not easily understandable in a consistent way. This makes it obvious that currently it is an interface functionality. Having this in eGo could help to not misinterpret this method...

**Comment by ulfmueller** [comment]
one remark: the disagg function needs the orginal_network which represents the full complexity and the clustered network. The etrago function currently just returns the final network.

**Comment by maltesc** [comment]
For this reason:

> one remark: the disagg function needs the orginal_network which represents the full complexity and the clustered network. The etrago function currently just returns the final network.

I would suggest to leave the functionality in eTraGo. One could argue that **eTraGo must meet the interface requirements** in order to be used in eGo. Since the clustering is merely a eTraGo-specific functionality, also the desaggregation should be an eTraGo thing. Thereby, it can be assured that eGo only 'sees' a consistent eTraGo data-set and doesn't have to bother about desaggregation.

**I consider this a clearer distinction between eGo en eTraGo.**

**Comment by ulfmueller** [comment]
The problem is, the disaggregation is clearly focused on the interface. If you use it, it will overwrite the nodal results of the clustered results with the ones from the disaggregation of the original network. But right now we will not recalculate power flows. I think a fully disaggregated data set would create a pseudo level of detail and accuracy. That is why I think it is a clear 'interface functionality'.
@maltesc do you understand the reasoning? Does it make sense?

Practically we can also leave it in eTraGo. Then the user just has to be careful (more than normal maybe :wink: ) once using the desagg function...

@gnn Do you think it would be possible the the etrago() only returns the original_network, when clustering algorithms are applied? and then the desaggregation method would be outside of the etrago() function....
