### ISSUE TITLE
Weather ID for Interface and eDisGo

### ISSUE THREAD

**Issue by maltesc** [openego/eGo#49]
The interface function [get_etragospecs_direct()](https://github.com/openego/eGo/blob/features/edisgo_integration/ego/tools/specs.py#L390) considers different weather cells for each generator aggregate.

Currently, this information comes from the mview `model_draft.ego_supply_aggr_weather_mview`, based on the generator single table `model_draft.ego_supply_pf_generator_single`. The problem is, that neither the table nor the mview are versioned. 

Before I shift the big generator single table into the versioned schema, I am thinking about alternative ways of identifying the weather IDs for each generator aggregate. Does anyone have an idea? @gplssm, have you solved the weather ID allocation in eDisGo somehow?

**Comment by wolfbunke** [comment]
@maltesc what is the status of this issue?
