### ISSUE TITLE
csv import of eTraGo network(s) fails with lines-losses.csv

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGo#87]
Right now the importer cannot deal with the lines-losses.csv. As an intermediate-dirty solution this file has to be deleted beforehand. I think it would be good to ensure that these losses get imported as well.

**Comment by wolfbunke** [comment]
I fixed it in pypsa with https://github.com/openego/PyPSA/commit/3a3138d2687b12f84aa9e5bce7a862f6fc62a564
