### ISSUE TITLE
Consistent design for config / scenario setting parameters

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGo#91]
The scenario_setting.json in eGo defines what options/parameters are chosen for calculation. 
We have to check and probably restructure this file which is sub-divided into 'global', 'eTraGo' and 'eDisGo'. 
For eTraGo the settings 'args' from eTraGo are totally part of that eGo settings file. For eDisGo many config parameters are set only within eDisGo (so far). We should find a consistent and clear work flow here.

To give one example. The [db-connection](https://github.com/openego/eGo/blob/dev/ego/scenario_setting.json#L5) is part of the global eGo scenario settings. This value is set for eTraGo as well but not for eDisGo. eDisGo db connection is defined in eDisGo. So practically the tag 'global' is not being realized.

**Comment by wolfbunke** [comment]
I started to change the settings in here: https://github.com/openego/eGo/tree/features/change-settings/ego 
- global changed to eGo
- results_id and recover are meld to results_id

A more detailed design idea follows.

**Comment by wolfbunke** [comment]
Design ideas for the scenario_setting file:

**A)** merge results (csv export) together and add this to `"eGo"`
A function in utilities automatize saves the results csv in a result folder. For example: settings ( `... "eGo" { ... "results": "results/NEP_full_calculation" ...}`) and creates:

> "results/NEP_full_calculation" (upcoming ego results csv)
> "results/NEP_full_calculation/eTraGo"
> "results/NEP_full_calculation/eTraGo/disaggregated"
>  "results/NEP_full_calculation/eDisGo"

**B)** The gridversion of eGo also needs to effect the eDisGo settings/config in ` .edisGo/config/config_db_tables.cfg`
Here `[version]`, `[model_draft]` or `[versioned]` should be manipulated by the eGo settings.   A logger.info could additional point to the path where the other eDisGo settings are stored.
   
**C)** The parallelisation is used in eTraGo and eDisGo and could be moved to eGo?

**D)** export: At the moment only eTraGo has a database export together with the upcoming eGo export those setting can be merged to eGo as export.
For example like: export: `["null", "eTraGo", "eGo", "all"]`

**E)** start_ and and end_snapshot could move to eGo.
